// SPDX-License-Identifier: Apache-2.0
/**
 * English (en) message catalog.
 *
 * In production this file is generated by ``npm run i18n:compile`` from
 * messages.po. The hand-written entries below are the comprehensive
 * v12.0 catalog covering all 17 feature modules and the navigation
 * shell. Lingui macros at component boundaries pull these strings;
 * non-translated literals stay in source for compile-time checks.
 */
export const messages = {
  // ── Navigation (Carbon SideNav) ───────────────────────────────────────
  'nav.group.live': 'Live',
  'nav.group.engines': 'Engines',
  'nav.group.workloads': 'Workloads',
  'nav.group.health': 'Health',
  'nav.group.admin': 'Admin',
  'nav.overview': 'Overview',
  'nav.fleet': 'Fleet',
  'nav.hosts': 'Hosts',
  'nav.containers': 'Containers',
  'nav.engines': 'Engines',
  'nav.pins': 'Pins',
  'nav.patches': 'Patches',
  'nav.drift': 'Drift',
  'nav.bench': 'Bench',
  'nav.chat': 'Chat',
  'nav.jobs': 'Jobs',
  'nav.doctor': 'Doctor',
  'nav.evidence': 'Evidence',
  'nav.configs': 'Configs',
  'nav.licensing': 'Licensing',
  'nav.auth': 'Auth',
  'nav.settings': 'Settings',

  // ── Common ────────────────────────────────────────────────────────────
  'common.loading': 'Loading…',
  'common.error': 'An error occurred',
  'common.retry': 'Retry',
  'common.cancel': 'Cancel',
  'common.confirm': 'Confirm',
  'common.save': 'Save',
  'common.close': 'Close',
  'common.clear': 'Clear',
  'common.send': 'Send',
  'common.no_data': 'No data',
  'common.last_run': 'Last run',
  'common.summary': 'Summary',
  'common.timestamp': 'When',
  'common.model': 'Model',
  'common.pin': 'Pin',
  'common.engine': 'Engine',

  // ── Status / tags ─────────────────────────────────────────────────────
  'status.applied': 'Applied',
  'status.skipped': 'Skipped',
  'status.failed': 'Failed',
  'status.drift': 'Drift detected',
  'status.ok': 'OK',
  'status.online': 'Online',
  'status.offline': 'Offline',
  'status.degraded': 'Degraded',
  'status.unknown': 'Unknown',
  'status.running': 'Running',
  'status.exited': 'Exited',
  'status.paused': 'Paused',
  'status.created': 'Created',
  'status.dead': 'Dead',
  'status.restarting': 'Restarting',
  'status.queued': 'Queued',
  'status.succeeded': 'Succeeded',
  'status.canceled': 'Canceled',
  'status.pending': 'Pending',
  'status.regression': 'Regression',
  'status.warning': 'Warning',
  'status.info': 'Info',
  'status.error': 'Error',
  'status.critical': 'Critical',

  // ── Tiers ─────────────────────────────────────────────────────────────
  'tier.community': 'Community',
  'tier.engine': 'Engine (commercial)',

  // ── Overview ──────────────────────────────────────────────────────────
  'overview.title': 'Overview',
  'overview.fleet.title': 'Fleet',
  'overview.containers.title': 'Containers',
  'overview.patches.title': 'Patches',
  'overview.doctor.title': 'Doctor',
  'overview.evidence.title': 'Evidence',
  'overview.api_version': 'API version',

  // ── Fleet ─────────────────────────────────────────────────────────────
  'fleet.title': 'Fleet',
  'fleet.total_hosts': 'Total hosts',
  'fleet.online': 'Online',
  'fleet.degraded': 'Degraded',
  'fleet.offline': 'Offline',
  'fleet.unknown': 'Unknown',
  'fleet.gpus': 'GPUs',
  'fleet.vram': 'VRAM (GiB)',

  // ── Hosts ─────────────────────────────────────────────────────────────
  'hosts.title': 'Hosts',
  'hosts.empty': 'No hosts in fleet',
  'hosts.col.hostname': 'Hostname',
  'hosts.col.status': 'Status',
  'hosts.col.sndr_version': 'sndr',
  'hosts.col.engine': 'Engine',
  'hosts.col.gpus': 'GPUs',
  'hosts.col.ram': 'RAM',

  // ── Containers ────────────────────────────────────────────────────────
  'containers.title': 'Containers',
  'containers.empty': 'No containers running',
  'containers.col.name': 'Name',
  'containers.col.state': 'State',
  'containers.col.image': 'Image',
  'containers.col.model': 'Model',
  'containers.col.engine': 'Engine',
  'containers.col.ports': 'Ports',

  // ── Engines ───────────────────────────────────────────────────────────
  'engines.title': 'Engines',
  'engines.selector.title': 'Engine',
  'engines.selector.placeholder': 'Select an engine',
  'engines.unavailable.suffix': '(unavailable)',

  // ── Pins ──────────────────────────────────────────────────────────────
  'pins.title': 'Pins',
  'pins.empty': 'No pin manifests',
  'pins.col.pin': 'Pin',
  'pins.col.status': 'Status',
  'pins.col.full_version': 'Full version',
  'pins.col.manifest': 'Manifest',
  'pins.col.drift': 'Drift',
  'pins.col.bench': 'Bench (TPS)',

  // ── Patches ───────────────────────────────────────────────────────────
  'patches.title': 'Patches',
  'patches.inventory.title': 'Inventory',
  'patches.inventory.total': 'Total',
  'patches.inventory.active': 'Active',
  'patches.inventory.retired': 'Retired',
  'patches.inventory.enabled_now': 'Enabled now',
  'patches.inventory.engine_tier': 'Engine tier',
  'patches.filter.family': 'Family',
  'patches.filter.tier': 'Tier',
  'patches.filter.lifecycle': 'Lifecycle',
  'patches.filter.enabled_only': 'Enabled in live env only',
  'patches.col.id': 'ID',
  'patches.col.title': 'Title',
  'patches.col.family': 'Family',
  'patches.col.tier': 'Tier',
  'patches.col.lifecycle': 'Lifecycle',
  'patches.col.default_on': 'Default',
  'patches.col.enabled_now': 'Enabled',

  // ── Drift ─────────────────────────────────────────────────────────────
  'drift.title': 'Drift',

  // ── Bench ─────────────────────────────────────────────────────────────
  'bench.title': 'Bench',
  'bench.empty': 'No bench runs yet',
  'bench.col.wall_tps': 'wall TPS',
  'bench.col.tpot': 'TPOT ms',
  'bench.col.ttft': 'TTFT ms',
  'bench.col.cv': 'CV',
  'bench.col.outcome': 'Outcome',

  // ── Chat ──────────────────────────────────────────────────────────────
  'chat.title': 'Chat',
  'chat.endpoint': 'Endpoint',
  'chat.model': 'Model',
  'chat.placeholder': 'Type a message…',
  'chat.send_hint': 'Send (⌘+⏎)',
  'chat.no_messages': 'No messages yet. Type below to start.',
  'chat.generating': 'Generating…',

  // ── Jobs ──────────────────────────────────────────────────────────────
  'jobs.title': 'Jobs',
  'jobs.empty': 'No jobs',
  'jobs.col.id': 'ID',
  'jobs.col.kind': 'Kind',
  'jobs.col.state': 'State',
  'jobs.col.progress': 'Progress',
  'jobs.col.started': 'Started',

  // ── Doctor ────────────────────────────────────────────────────────────
  'doctor.title': 'Doctor',
  'doctor.healthy': 'All healthy',
  'doctor.issues': 'Issues found',
  'doctor.no_findings': 'No findings (everything green)',
  'doctor.col.severity': 'Severity',
  'doctor.col.category': 'Category',
  'doctor.col.finding': 'Title',
  'doctor.col.remediation': 'Remediation',

  // ── Evidence ──────────────────────────────────────────────────────────
  'evidence.title': 'Evidence',
  'evidence.release_readiness': 'Release-readiness',
  'evidence.col.id': 'ID',
  'evidence.col.name': 'Gate',
  'evidence.col.status': 'Status',

  // ── Configs ───────────────────────────────────────────────────────────
  'configs.title': 'Configs',
  'configs.tab.models': 'Models',
  'configs.tab.hardware': 'Hardware',
  'configs.tab.profiles': 'Profiles',
  'configs.tab.presets': 'Presets',

  // ── Licensing ─────────────────────────────────────────────────────────
  'licensing.title': 'Licensing',

  // ── Auth ──────────────────────────────────────────────────────────────
  'auth.title': 'Auth',
  'auth.session_status': 'Session status',
  'auth.authenticated': 'Authenticated',
  'auth.token_preview': 'Token preview',
  'auth.api_token': 'API token',
  'auth.token_placeholder': 'sndr_…',
  'auth.token_label': 'Bearer token for the API',

  // ── Settings ──────────────────────────────────────────────────────────
  'settings.title': 'Settings',
  'settings.locale': 'Locale',
  'settings.locale.label': 'Interface language',
  'settings.engine': 'Active engine',
  'settings.api_endpoint': 'API endpoint',
  'settings.api_endpoint.label': 'Override API base URL (empty = same-origin)',
  'settings.about': 'About',
  'settings.version': 'Version',
  'settings.theme': 'Theme',
  'settings.i18n': 'i18n',
} as const;

export type MessageKey = keyof typeof messages;
